<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2gbiqSR\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2gbiqSR/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2gbiqSR.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2gbiqSR\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container2gbiqSR\srcDevDebugProjectContainer(array(
    'container.build_hash' => '2gbiqSR',
    'container.build_id' => '7094953a',
    'container.build_time' => 1522933232,
), __DIR__.\DIRECTORY_SEPARATOR.'Container2gbiqSR');
